### PR TITLE
Update credo dependency to fix warning

### PR DESCRIPTION
**Pull request by theodowling**
Resolve issue #90 

I've also updated dependencies and fixed some credo warnings.

### CODE REVIEW

**Comment by nelsonic** [comment]
Travis-CI build appears to fail because app cannot connect to Postgres ...
```
connection refused - :econnrefused
```
https://travis-ci.org/dwyl/library/builds/593206304#L428
image

**Comment by nelsonic** [comment]
image

Going to restart/rerun the build on this PR and see if it passes in light of: #94 (added postgres) ...

**Comment by nelsonic** [comment]
@theodowling looks like the PR won't pass CI until you either rebase on `master` or add the lines:
```yml
services: # ensure that Travis-CI provisions a DB for our tests
  - postgresql
```
to the `.travis.yml` file.

https://travis-ci.org/dwyl/library/builds/593679274#L466
image

Thanks for the PR BTW! 🥇

**Comment by theodowling** [comment]
Thanks for the tip @nelsonic - rebasing resolved the travis issue.

**Pull request merged**
