### PR TITLE
Initialise phoenix app

### PR DESCRIPTION
**Pull request by finnhodgkin**
Adds configuration for pre-commit and dependencies. 

#3 #2

### CODE REVIEW

**Comment by ZooeyMiller** [comment]
Just realised @katbow isn't available until Monday, so @finnhodgkin and I are thinking to merge this in as it's a blocker for the rest of our work.

**Comment by katbow** [comment]
@ZooeyMiller I have a bit of time now. Will review now

**Comment by ZooeyMiller** [comment]
@katbow That's a good point RE: travis, we should set that up now, in this PR. Will do so now.

**Comment by katbow** [comment]
@ZooeyMiller sweet, just reassign me when ready!

**Pull request merged**
